import "~/styles/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from '@clerk/themes';

import { Inter } from "next/font/google";
import { TopNav } from "~/components/TopNav";
import { Toaster } from "~/components/ui/sonner";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider appearance={{
      baseTheme: dark
    }}>
      <html lang="en">
        <body className={`font-sans ${inter.variable} h-screen w-screen bg-black text-white max-w-[100vh] flex-col dark`}>
          <TopNav />
          {children}
          <Toaster richColors />
          </body>
      </html>
    </ClerkProvider>
  );
}
